spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    koreaStockQueue: koreaStockQueue
    koreaStockExchange: koreaStockExchange
    koreaStockRoutingKey: koreaStockRoutingKey
    usaStockQueue: usaStockQueue
    usaStockExchange: usaStockExchange
    usaStockRoutingKey: usaStockRoutingKey
